### ISSUE TITLE
Unable to login after running

### ISSUE THREAD

**Issue by zackskeeter** [pihomeserver/Kupiki-Hotspot#4]
Hey

I'm having an issue with your script. 
I cannot login to the oova captivate page.

If i open up terminal and execute this, it works. 
`echo 'insert into radcheck (username, attribute, op, value) values ("usertest", "Password", "==", "passwd");' | mysql -u root -p$MYSQL_PASSWORD;`

however, if I paste this into the rc.local, it is not added. How would I add this?

Also, once i do login, i am not able to navigate to deloradius. The server just never responds. 

This really awesome work! Just need a little advice on the issue

**Comment by zackskeeter** [comment]
Also, i just pulled down the latest, my pi boots and the install runs. However no wifi hotspot comes up and when i try and run a command like `mysql` it says command not found. Can you double check this on your side?

**Comment by pihomeserver** [comment]
Hello. As explained in the README there is a log file in /var/log. Look at it and search for error messages. Also if you don't find any, run manually the script to see if there is any crash
I checked the script last weekend  on a Pi3 withminibian and it ended successfully with a hotspot and daloradius ready

**Comment by zackskeeter** [comment]
Ahh, I see the log exits with `"Please reboot and run the script again"` Out of interest, how to I actually run the script again?

**Comment by pihomeserver** [comment]
For the distro just reboot and it will run again
-------- Message d'origine --------De : zackskeeter <notifications@github.com> Date : 01/02/2017  18:53  (GMT+01:00) À : pihomeserver/Kupiki-Hotspot <Kupiki-Hotspot@noreply.github.com> Cc : Pi Home Server <pihomeserver@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [pihomeserver/Kupiki-Hotspot] Unable to login after running (#4) 
Ahh, I see the log exits with "Please reboot and run the script again" Out of interest, how to I actually run the script again?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pihomeserver/Kupiki-Hotspot","title":"pihomeserver/Kupiki-Hotspot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pihomeserver/Kupiki-Hotspot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zackskeeter in #4: Ahh, I see the log exits with `\"Please reboot and run the script again\"` Out of interest, how to I actually run the script again? "}],"action":{"name":"View Issue","url":"https://github.com/pihomeserver/Kupiki-Hotspot/issues/4#issuecomment-276729824"}}}

**Comment by zackskeeter** [comment]
Ahh of course! Thank you. 

So i am able to connect now,  but i still have the issue where I cannot login. What's the default password and user for this screen?

![image](https://cloud.githubusercontent.com/assets/5071223/22527025/a47fe1ce-e89b-11e6-9709-1195cc1a85b3.png)

**Comment by pihomeserver** [comment]
Good news. Connect to the daloradius Web page using default credentials  (check the end of the log file or the readme on git) and create a user from the interface. Look at the tutorial on my site if neededI guess that I have to update the documentation ;-)
-------- Message d'origine --------De : zackskeeter <notifications@github.com> Date : 01/02/2017  22:30  (GMT+01:00) À : pihomeserver/Kupiki-Hotspot <Kupiki-Hotspot@noreply.github.com> Cc : Pi Home Server <pihomeserver@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [pihomeserver/Kupiki-Hotspot] Unable to login after running (#4) 
Ahh of course! Thank you.
So i am able to connect now,  but i still have the issue where I cannot login. What's the default password and user for this screen?


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pihomeserver/Kupiki-Hotspot","title":"pihomeserver/Kupiki-Hotspot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pihomeserver/Kupiki-Hotspot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zackskeeter in #4: Ahh of course! Thank you. \r\n\r\nSo i am able to connect now,  but i still have the issue where I cannot login. What's the default password and user for this screen?\r\n\r\n![image](https://cloud.githubusercontent.com/assets/5071223/22527025/a47fe1ce-e89b-11e6-9709-1195cc1a85b3.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/pihomeserver/Kupiki-Hotspot/issues/4#issuecomment-276788309"}}}
